##### 도서 쇼핑몰 프로젝트 테이블 생성 SQL #####

### 생성 예상 테이블 ###
# 1. 회원 정보 테이블 SHOP_MEMBER
# 2. 도서 카테고리 테이블 BOOK_CATEGORY
# 3. 도서 정보 테이블 SHOP_BOOK
# 4. 장바구니 테이블 SHOP_CART
# 5. 구매 정보 테이블 SHOP_BUY

# 회원 정보 테이블 생성
CREATE TABLE SHOP_MEMBER (
	MEM_EMAIL VARCHAR(50) PRIMARY KEY,
	MEM_PW VARCHAR(100) NOT NULL, # 암호화를 위해 사이즈 증가
	MEM_NAME VARCHAR(30) NOT NULL,
	MEM_TEL VARCHAR(15) NOT NULL UNIQUE, # '-' 포함
	MEM_ADDR VARCHAR(50),
	ADDR_DETAIL VARCHAR(100),
	IS_USING VARCHAR(10) DEFAULT 'Y', # 'Y': 사용중, 'N': 사용 안 함
	MEM_ROLE VARCHAR(20) DEFAULT 'USER', # USER: 회원, MANAGER: 쇼핑몰 운영자, ADMIN: 관리자
	JOIN_DATE DATETIME DEFAULT SYSDATE(),
	PROVIDER VARCHAR(20) DEFAULT 'local', # 원래 불필요 SNS 연동을 위해 추가
	PROVIDER_ID VARCHAR(100) # 원래 불필요 SNS 연동을 위해 추가
);

# 도서 카테고리 정보
CREATE TABLE BOOK_CATEGORY (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT,
	CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

# 카테고리 기본 데이터 INSERT
INSERT INTO BOOK_CATEGORY 
VALUES 
(1, 'IT/인터넷'), 
(2, '자기계발'), 
(3, '소셜/에세이');

# 도서 정보 테이블
CREATE TABLE SHOP_BOOK (
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT,
	BOOK_TITLE VARCHAR(30) NOT NULL,
	AUTHOR VARCHAR(20) NOT NULL,
	BOOK_PRICE INT NOT NULL,
	BOOK_STOCK INT DEFAULT 10,
	BOOK_INTRO VARCHAR(150), # 50 -> 150으로 변경됨
	PUBLISH_DATE DATETIME, # 출판일
	CATE_NUM INT REFERENCES BOOK_CATEGORY (CATE_NUM)
);

# 도서 이미지 정보 테이블
CREATE TABLE BOOK_IMG (
	IMG_NUM	INT PRIMARY KEY AUTO_INCREMENT,
	ORIGIN_FILE_NAME VARCHAR(100),			# 원본 파일명
	UPLOAD_FILE_NAME VARCHAR(100),			# 첨부된 파일명
	IS_MAIN VARCHAR(1) NOT NULL,			# 대표이미지 여부('Y', 'N')
	BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) ON DELETE CASCADE
);

# 장바구니 테이블 SHOP_CART
CREATE TABLE SHOP_CART (
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT,							# 장바구니 번호
	BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM),				# 상품번호
	CART_CNT INT NOT NULL,												# 장바구니에 담은 수량
	MEM_EMAIL VARCHAR(50) NOT NULL REFERENCES SHOP_MEMBER (MEM_EMAIL),	# 장바구니 주인 EMAIL
	CART_DATE DATETIME DEFAULT SYSDATE()	 							# 장바구니에 담은 날짜
);

# 구매 정보 테이블 SHOP_BUY
CREATE TABLE SHOP_BUY (
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT,						# 구매 번호
	BUY_PRICE INT NOT NULL,										# 총 구매 금액
	MEM_EMAIL VARCHAR(20) REFERENCES SHOP_MEMBER (MEM_EMAIL),	# 구매자 Email
	BUY_DATE DATETIME DEFAULT SYSDATE()							# 구매일
);

# 구매 상세 테이블 BUY_DETAIL
CREATE TABLE BUY_DETAIL (
	BUY_DETAIL_NUM INT PRIMARY KEY AUTO_INCREMENT,				# 구매 상세 번호
	BOOK_NUM INT REFERENCES SHOP_BOOK (BOOK_NUM),				# 상품번호
	BUY_CNT INT NULL,											# 구매 수량
	BUY_PRICE INT NOT NULL,										# 구매 금액
	BUY_NUM INT REFERENCES SHOP_BUY (BUY_NUM)					# 구매 번호
);